version: "3.5"

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - '5432:5432'
  message_app:
    depends_on:
      - db
    image: app
    build: .
    ports:
      - "8081:8080"
    environment:
       - DATABASE_URL=jdbc:postgresql://db:5432/postgres
       - DATABASE_USERNAME=postgres
       - DATABASE_PASSWORD=12345
    deploy:
      replicas: 3
volumes:
  pgdata: {}