version: "3.5"

services:
  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: text_db
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  message_app:
    depends_on:
      - db
    #container_name: app
    #image: app
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://localhost:3306/text_db
      - DATABASE_USERNAME=usuario
      - DATABASE_PASSWORD=12345
volumes:
  db: